-- =============================================================================
-- chapters/src/c001/c001.sql
-- AUTO-GENERATED by chapters/scripts/parse.py
-- DO NOT EDIT BY HAND. Edit c001.json instead.
-- =============================================================================

BEGIN TRANSACTION;

-- shared_data (story catalogue, consumed by gameConsole)
INSERT OR REPLACE INTO shared_data (idStory, storyName, idChapter, chapterName, minScore, minSpeed, minRetries, requiredStories, nextBlockScore, nextBlockSpeed, tableMatrix, xmlDialogue, thumbnailPath) VALUES (1, 'Falling Sky', 1, 'The Tetris Matrix', 0, 0.0, 0, '', 50, 1.0, '', '', 'THUMB_001_FALLING_SKY.png');
INSERT OR REPLACE INTO shared_data (idStory, storyName, idChapter, chapterName, minScore, minSpeed, minRetries, requiredStories, nextBlockScore, nextBlockSpeed, tableMatrix, xmlDialogue, thumbnailPath) VALUES (2, 'Holy Sanctum', 1, 'The Tetris Matrix', 2, 0.1, 1, '1', 100, 1.2, '', '', 'THUMB_002_ORDERCORP_TEMPLE.png');
INSERT OR REPLACE INTO shared_data (idStory, storyName, idChapter, chapterName, minScore, minSpeed, minRetries, requiredStories, nextBlockScore, nextBlockSpeed, tableMatrix, xmlDialogue, thumbnailPath) VALUES (3, 'Blood Tower', 1, 'The Tetris Matrix', 1, 0.1, 2, '1', 100, 1.2, '', '', 'THUMB_003_UNDERCITY_SLUM.png');
INSERT OR REPLACE INTO shared_data (idStory, storyName, idChapter, chapterName, minScore, minSpeed, minRetries, requiredStories, nextBlockScore, nextBlockSpeed, tableMatrix, xmlDialogue, thumbnailPath) VALUES (4, 'Quantum Leap', 1, 'The Tetris Matrix', 1, 1.1, 1, '1,2,3', 100, 1.2, '', '', 'THUMB_004_SHADOW_ALLEY.png');
INSERT OR REPLACE INTO shared_data (idStory, storyName, idChapter, chapterName, minScore, minSpeed, minRetries, requiredStories, nextBlockScore, nextBlockSpeed, tableMatrix, xmlDialogue, thumbnailPath) VALUES (5, 'Sanctified', 1, 'The Tetris Matrix', 20, 0.1, 1, '2', 200, 1.5, '', '', 'THUMB_005_HEAVEN_MATRIX.png');
INSERT OR REPLACE INTO shared_data (idStory, storyName, idChapter, chapterName, minScore, minSpeed, minRetries, requiredStories, nextBlockScore, nextBlockSpeed, tableMatrix, xmlDialogue, thumbnailPath) VALUES (6, 'Origin Glitch', 1, 'The Tetris Matrix', 1, 0.1, 20, '3', 200, 1.5, '', '', 'THUMB_006_GLITCH_VIRUS.png');
INSERT OR REPLACE INTO shared_data (idStory, storyName, idChapter, chapterName, minScore, minSpeed, minRetries, requiredStories, nextBlockScore, nextBlockSpeed, tableMatrix, xmlDialogue, thumbnailPath) VALUES (7, 'Algorithm Master', 1, 'The Tetris Matrix', 1, 10.1, 1, '4', 200, 1.5, '', '', 'THUMB_007_FROZEN_TIME.png');
INSERT OR REPLACE INTO shared_data (idStory, storyName, idChapter, chapterName, minScore, minSpeed, minRetries, requiredStories, nextBlockScore, nextBlockSpeed, tableMatrix, xmlDialogue, thumbnailPath) VALUES (8, 'Dead Wall', 1, 'The Tetris Matrix', 1, 0.1, 1, '5,6', 0, 0.0, '', '', 'THUMB_008_KILL_SCREEN.png');
INSERT OR REPLACE INTO shared_data (idStory, storyName, idChapter, chapterName, minScore, minSpeed, minRetries, requiredStories, nextBlockScore, nextBlockSpeed, tableMatrix, xmlDialogue, thumbnailPath) VALUES (9, 'Endless Record', 1, 'The Tetris Matrix', 1, 0.1, 1, '5,7', 0, 0.0, '', '', 'THUMB_009_ENDLESS_LOOP.png');
INSERT OR REPLACE INTO shared_data (idStory, storyName, idChapter, chapterName, minScore, minSpeed, minRetries, requiredStories, nextBlockScore, nextBlockSpeed, tableMatrix, xmlDialogue, thumbnailPath) VALUES (10, 'Maxout 999999', 1, 'The Tetris Matrix', 1, 0.1, 1, '5,6,7', 0, 0.0, '', '', 'THUMB_010_GOLDEN_MAXOUT.png');

COMMIT;
