#!/usr/bin/env python3
"""
build_manifest.py — Rebuild chapters/manifest.json from per-chapter git SHAs.

Usage:
    python3 chapters/scripts/build_manifest.py [REPO_ROOT]

If REPO_ROOT is omitted, the script auto-detects it by walking up from this
file's location until it finds a 'chapters/src' directory.

Output:
    Overwrites <REPO_ROOT>/chapters/manifest.json with:
        {
          "chapters": [
            { "id": "c001", "sha": "<latest commit SHA touching c001.json>" },
            { "id": "c002", "sha": "..." }
          ]
        }

Notes:
    - SHA is the latest commit that modified the chapter's c{id}.json file
      (NOT the media files — those have independent shas if needed).
    - If a chapter has no git history yet (newly added, not committed),
      its sha falls back to the literal string "uncommitted".
    - The script exits 0 even with zero chapters (empty manifest is valid).
"""

from __future__ import annotations
import json
import re
import subprocess
import sys
from pathlib import Path


def find_repo_root(start: Path) -> Path:
    """Walk up from `start` until 'chapters/src' is found; return that root."""
    for p in [start] + list(start.parents):
        if (p / "chapters" / "src").is_dir():
            return p
    raise SystemExit(
        f"ERROR: cannot locate 'chapters/src' from {start}. "
        f"Pass REPO_ROOT explicitly."
    )


def latest_sha(repo_root: Path, rel_path: Path) -> str:
    """git log -1 --format=%H -- <path>. Returns 'uncommitted' if empty."""
    try:
        out = subprocess.check_output(
            ["git", "log", "-1", "--format=%H", "--", str(rel_path)],
            cwd=str(repo_root),
            stderr=subprocess.DEVNULL,
        )
        sha = out.decode("utf-8", "ignore").strip()
        return sha if sha else "uncommitted"
    except (subprocess.CalledProcessError, FileNotFoundError):
        return "uncommitted"


def main(argv: list[str]) -> int:
    if len(argv) > 2:
        print(f"Usage: {argv[0]} [REPO_ROOT]", file=sys.stderr)
        return 2

    if len(argv) == 2:
        repo_root = Path(argv[1]).resolve()
    else:
        # Auto-detect: this script lives at <root>/chapters/scripts/build_manifest.py
        repo_root = find_repo_root(Path(__file__).resolve().parent)

    src_dir = repo_root / "chapters" / "src"
    if not src_dir.is_dir():
        print(f"ERROR: not a directory: {src_dir}", file=sys.stderr)
        return 2

    chapter_pat = re.compile(r"^c\d{3,}$")
    entries: list[dict[str, str]] = []
    for child in sorted(src_dir.iterdir()):
        if not child.is_dir() or not chapter_pat.fullmatch(child.name):
            continue
        json_file = child / f"{child.name}.json"
        if not json_file.is_file():
            print(f"  WARN: skipping {child.name}: no {json_file.name}", file=sys.stderr)
            continue
        rel = json_file.relative_to(repo_root)
        sha = latest_sha(repo_root, rel)
        entries.append({"id": child.name, "sha": sha})
        print(f"  {child.name}: {sha}")

    out = {
        "_note": "AUTO-GENERATED by .github/workflows/sync-chapters.yml. Do not edit by hand.",
        "chapters": entries,
    }
    out_path = repo_root / "chapters" / "manifest.json"
    out_path.write_text(json.dumps(out, indent=2) + "\n", encoding="utf-8")
    print(f"OK: wrote {out_path} ({len(entries)} chapter(s))")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
